feat: Add vim-scala plugin
zechris/nwaywood-dotfiles pull request #1
Opened 2022-08-19 09:04 UTC by zechris

(mainly just for sorting imports)

I liked this [vim-scala](https://github.com/derekwyatt/vim-scala) plugin from my go at using SpaceVim, and I see hey have it included [here](https://github.com/SpaceVim/SpaceVim/blob/caf1d8428aa0e210888e7d2d197594388beebf12/autoload/SpaceVim/layers/lang/scala.vim#L258-L262)...

but I'm not quite sure where/how to define the "which key" mapping for it in my lunarvim config.
(FYI I'd like to give it the mapping `"[space] l s"` so it can sit next to the `"[space] l f"" mapping for `Format` that auto-formats the code.)

Can you help me finish this PR to do that @nwaywood? 🙏

2022-08-20 08:20 UTC, nwaywood requested changes

2022-08-20 08:20 UTC, nwaywood commented on config/nvim/init.lua
> +require "user.plugins.vim-scala"
```suggestion
```

2022-08-20 08:20 UTC, nwaywood commented on config/nvim/init.lua
> +require "user.plugins.vim-scala"
This line isn't needed. These lines are file imports. 

e.g. `require "user.plugins.vim-scala"` would load the code in the file `/user/plugins/vim-scala.lua`. Since that file doesn't exist, this line does nothing

2022-08-20 08:20 UTC, nwaywood commented on config/nvim/lua/user/plugins/lsp.lua
> +	  s = { "<cmd>lua vim.vim-format.SortScalaImports()<CR>", "Sort Imports" },
```suggestion
	  s = { "<cmd>SortScalaImports<CR>", "Sort Imports" },
```

2022-08-20 08:20 UTC, nwaywood commented on config/nvim/lua/user/plugins.lua
> +  use "derekwyatt/vim-scala" -- only really using the https://github.com/derekwyatt/vim-scala#sorting-of-import-statements
Yep perfect! This is how you add a plugin, just remember to run  `:PackerSync` to install the new plugin. You can think of `:PackerSync` kind of like `brew upgrade`

2022-08-20 08:20 UTC, nwaywood commented on config/nvim/lua/user/plugins/lsp.lua
> +	  s = { "<cmd>lua vim.vim-format.SortScalaImports()<CR>", "Sort Imports" },
The `<cmd>` is the same as `:` when executing commands in Vim. 

e.g. Executing `:MetalsInstall` in Vim maps to `<cmd>MetalsInstall<CR>` in lua.

2022-08-20 08:20 UTC, nwaywood commented on config/nvim/lua/user/plugins/lsp.lua
> +	  s = { "<cmd>lua vim.vim-format.SortScalaImports()<CR>", "Sort Imports" },
That lua keyword is how you would execute lua code in Ex mode. e.g. `:lua vim.lsp.buf.formatting()`

2022-08-20 08:20 UTC, nwaywood commented on config/nvim/init.lua
> +require "user.plugins.vim-scala"
This is just a convention I use to organise my config. e.g. "I want to change the config for the comment plugin, that will be in the user.plugins.comment file"

2022-08-21 08:41 UTC, zechris commented
Thanks @nwaywood - that worked!

2022-08-21 08:41 UTC, merged